from aiogram.types import InlineKeyboardButton, InlineKeyboardMarkup, ReplyKeyboardMarkup, KeyboardButton

button_load = KeyboardButton('Загрузить')
button_delete = KeyboardButton('Удалить')
button_show = KeyboardButton('Показать загруженное')
Char = InlineKeyboardButton('characters', callback_data='add_characters')
Menu = InlineKeyboardButton('menu', callback_data='add_menu')
Prop = InlineKeyboardButton('properties', callback_data='add_properties')
Teams = InlineKeyboardButton('teams', callback_data='add_teams')
Weapons = InlineKeyboardButton('weapons', callback_data='add_weapons')
Arts = InlineKeyboardButton('artifacts', callback_data='add_artifacts')
Char_ = InlineKeyboardButton('characters', callback_data='dl_characters')
Menu_ = InlineKeyboardButton('menu', callback_data='dl_menu')
Prop_ = InlineKeyboardButton('properties', callback_data='dl_properties')
Teams_ = InlineKeyboardButton('teams', callback_data='dl_teams')
Weapons_ = InlineKeyboardButton('weapons', callback_data='dl_weapons')
Arts_ = InlineKeyboardButton('artifacts', callback_data='dl_artifacts')
CharShow = InlineKeyboardButton('characters', callback_data='show_characters')
MenuShow = InlineKeyboardButton('menu', callback_data='show_menu')
PropShow = InlineKeyboardButton('properties', callback_data='show_properties')
TeamsShow = InlineKeyboardButton('teams', callback_data='show_teams')
WeaponsShow = InlineKeyboardButton('weapons', callback_data='show_weapons')
ArtsShow = InlineKeyboardButton('artifacts', callback_data='show_artifacts')


button_case_admin = ReplyKeyboardMarkup(resize_keyboard=True).add(button_show).row(button_load, button_delete)
button_case_admin2 = InlineKeyboardMarkup(resize_keyboard=True).row(Char, Menu, Prop).row(Teams, Weapons, Arts)
button_case_admin3 = InlineKeyboardMarkup(resize_keyboard=True).row(Char_, Menu_, Prop_).row(Teams_, Weapons_, Arts_)
button_case_admin4 = InlineKeyboardMarkup(resize_keyboard=True).row(CharShow, MenuShow, PropShow).row(TeamsShow, WeaponsShow, ArtsShow)
